/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef BUNGA_H
#define BUNGA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Message bunga.ExecuteCommandReq.
 */
struct bunga_execute_command_req_repeated_t {
    int length;
    struct bunga_execute_command_req_t *items_p;
};

struct bunga_execute_command_req_t {
    struct pbtools_message_base_t base;
    char *command_p;
};

/**
 * Enum bunga.ClientToServer.messages.
 */
enum bunga_client_to_server_messages_choice_e {
    bunga_client_to_server_messages_choice_none_e = 0,
    bunga_client_to_server_messages_choice_execute_command_req_e = 1
};

/**
 * Oneof bunga.ClientToServer.messages.
 */
struct bunga_client_to_server_messages_oneof_t {
    enum bunga_client_to_server_messages_choice_e choice;
    union {
        struct bunga_execute_command_req_t execute_command_req;
    } value;
};

/**
 * Message bunga.ClientToServer.
 */
struct bunga_client_to_server_repeated_t {
    int length;
    struct bunga_client_to_server_t *items_p;
};

struct bunga_client_to_server_t {
    struct pbtools_message_base_t base;
    struct bunga_client_to_server_messages_oneof_t messages;
};

/**
 * Enum bunga.ExecuteCommandRsp.Kind.
 */
enum bunga_execute_command_rsp_kind_e {
    bunga_execute_command_rsp_kind_ok_e = 0,
    bunga_execute_command_rsp_kind_error_e = 1,
    bunga_execute_command_rsp_kind_output_e = 2
};

/**
 * Message bunga.ExecuteCommandRsp.
 */
struct bunga_execute_command_rsp_repeated_t {
    int length;
    struct bunga_execute_command_rsp_t *items_p;
};

struct bunga_execute_command_rsp_t {
    struct pbtools_message_base_t base;
    enum bunga_execute_command_rsp_kind_e kind;
    char *output_p;
    char *error_p;
};

/**
 * Enum bunga.ServerToClient.messages.
 */
enum bunga_server_to_client_messages_choice_e {
    bunga_server_to_client_messages_choice_none_e = 0,
    bunga_server_to_client_messages_choice_execute_command_rsp_e = 1
};

/**
 * Oneof bunga.ServerToClient.messages.
 */
struct bunga_server_to_client_messages_oneof_t {
    enum bunga_server_to_client_messages_choice_e choice;
    union {
        struct bunga_execute_command_rsp_t execute_command_rsp;
    } value;
};

/**
 * Message bunga.ServerToClient.
 */
struct bunga_server_to_client_repeated_t {
    int length;
    struct bunga_server_to_client_t *items_p;
};

struct bunga_server_to_client_t {
    struct pbtools_message_base_t base;
    struct bunga_server_to_client_messages_oneof_t messages;
};

/**
 * Encoding and decoding of bunga.ExecuteCommandReq.
 */
struct bunga_execute_command_req_t *
bunga_execute_command_req_new(
    void *workspace_p,
    size_t size);

int bunga_execute_command_req_encode(
    struct bunga_execute_command_req_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int bunga_execute_command_req_decode(
    struct bunga_execute_command_req_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

void bunga_client_to_server_messages_execute_command_req_init(
    struct bunga_client_to_server_t *self_p);

/**
 * Encoding and decoding of bunga.ClientToServer.
 */
struct bunga_client_to_server_t *
bunga_client_to_server_new(
    void *workspace_p,
    size_t size);

int bunga_client_to_server_encode(
    struct bunga_client_to_server_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int bunga_client_to_server_decode(
    struct bunga_client_to_server_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of bunga.ExecuteCommandRsp.
 */
struct bunga_execute_command_rsp_t *
bunga_execute_command_rsp_new(
    void *workspace_p,
    size_t size);

int bunga_execute_command_rsp_encode(
    struct bunga_execute_command_rsp_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int bunga_execute_command_rsp_decode(
    struct bunga_execute_command_rsp_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

void bunga_server_to_client_messages_execute_command_rsp_init(
    struct bunga_server_to_client_t *self_p);

/**
 * Encoding and decoding of bunga.ServerToClient.
 */
struct bunga_server_to_client_t *
bunga_server_to_client_new(
    void *workspace_p,
    size_t size);

int bunga_server_to_client_encode(
    struct bunga_server_to_client_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int bunga_server_to_client_decode(
    struct bunga_server_to_client_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void bunga_execute_command_req_init(
    struct bunga_execute_command_req_t *self_p,
    struct pbtools_heap_t *heap_p);

void bunga_execute_command_req_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct bunga_execute_command_req_t *self_p);

void bunga_execute_command_req_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct bunga_execute_command_req_t *self_p);

void bunga_execute_command_req_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct bunga_execute_command_req_repeated_t *repeated_p);

void bunga_execute_command_req_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct bunga_execute_command_req_repeated_t *repeated_p);

void bunga_client_to_server_init(
    struct bunga_client_to_server_t *self_p,
    struct pbtools_heap_t *heap_p);

void bunga_client_to_server_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct bunga_client_to_server_t *self_p);

void bunga_client_to_server_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct bunga_client_to_server_t *self_p);

void bunga_client_to_server_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct bunga_client_to_server_repeated_t *repeated_p);

void bunga_client_to_server_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct bunga_client_to_server_repeated_t *repeated_p);

void bunga_execute_command_rsp_init(
    struct bunga_execute_command_rsp_t *self_p,
    struct pbtools_heap_t *heap_p);

void bunga_execute_command_rsp_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct bunga_execute_command_rsp_t *self_p);

void bunga_execute_command_rsp_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct bunga_execute_command_rsp_t *self_p);

void bunga_execute_command_rsp_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct bunga_execute_command_rsp_repeated_t *repeated_p);

void bunga_execute_command_rsp_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct bunga_execute_command_rsp_repeated_t *repeated_p);

void bunga_server_to_client_init(
    struct bunga_server_to_client_t *self_p,
    struct pbtools_heap_t *heap_p);

void bunga_server_to_client_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct bunga_server_to_client_t *self_p);

void bunga_server_to_client_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct bunga_server_to_client_t *self_p);

void bunga_server_to_client_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct bunga_server_to_client_repeated_t *repeated_p);

void bunga_server_to_client_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct bunga_server_to_client_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
