/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020, Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* This file was generated by Messi. */

#ifndef BUNGA_SERVER_H
#define BUNGA_SERVER_H

#include <stdint.h>
#include "messi.h"
#include "bunga.h"

struct bunga_server_t;
struct bunga_server_client_t;

typedef void (*bunga_server_on_execute_command_req_t)(
    struct bunga_server_t *self_p,
    struct bunga_server_client_t *client_p,
    struct bunga_execute_command_req_t *message_p);

enum bunga_server_client_input_state_t {
    bunga_server_client_input_state_header_t = 0,
    bunga_server_client_input_state_payload_t
};

typedef void (*bunga_server_on_client_connected_t)(
    struct bunga_server_t *self_p,
    struct bunga_server_client_t *client_p);

typedef void (*bunga_server_on_client_disconnected_t)(
    struct bunga_server_t *self_p,
    struct bunga_server_client_t *client_p);

struct bunga_server_t {
    struct {
        char address[16];
        int port;
    } server;
    bunga_server_on_client_connected_t on_client_connected;
    bunga_server_on_client_disconnected_t on_client_disconnected;
    bunga_server_on_execute_command_req_t on_execute_command_req;
    int epoll_fd;
    messi_epoll_ctl_t epoll_ctl;
    int listener_fd;
    struct bunga_server_client_t *current_client_p;
    struct {
        struct bunga_server_client_t *connected_list_p;
        struct bunga_server_client_t *free_list_p;
        struct bunga_server_client_t *pending_disconnect_list_p;
        size_t input_buffer_size;
    } clients;
    struct {
        struct bunga_client_to_server_t *message_p;
        struct messi_buffer_t workspace;
    } input;
    struct {
        struct bunga_server_to_client_t *message_p;
        struct messi_buffer_t workspace;
        struct messi_buffer_t encoded;
    } output;
};

struct bunga_server_client_t {
    int client_fd;
    int keep_alive_timer_fd;
    struct {
        enum bunga_server_client_input_state_t state;
        struct messi_buffer_t data;
        size_t size;
        size_t left;
    } input;
    struct bunga_server_client_t *next_p;
    struct bunga_server_client_t *prev_p;
};

/**
 * Initialize given server.
 */
int bunga_server_init(
    struct bunga_server_t *self_p,
    const char *server_uri_p,
    struct bunga_server_client_t *clients_p,
    int clients_max,
    uint8_t *clients_input_bufs_p,
    size_t client_input_size,
    uint8_t *message_buf_p,
    size_t message_size,
    uint8_t *workspace_in_buf_p,
    size_t workspace_in_size,
    uint8_t *workspace_out_buf_p,
    size_t workspace_out_size,
    bunga_server_on_client_connected_t on_client_connected,
    bunga_server_on_client_disconnected_t on_client_disconnected,
    bunga_server_on_execute_command_req_t on_execute_command_req,
    int epoll_fd,
    messi_epoll_ctl_t epoll_ctl);

/**
 * Start serving clients.
 */
int bunga_server_start(struct bunga_server_t *self_p);

/**
 * Stop serving clients.
 */
void bunga_server_stop(struct bunga_server_t *self_p);

/**
 * Process any pending events on given file descriptor if it belongs
 * to given server.
 */
void bunga_server_process(struct bunga_server_t *self_p, int fd, uint32_t events);

/**
 * Send prepared message to given client.
 */
void bunga_server_send(
    struct bunga_server_t *self_p,
    struct bunga_server_client_t *client_p);

/**
 * Send prepared message to current client.
 */
void bunga_server_reply(struct bunga_server_t *self_p);

/**
 * Broadcast prepared message to all clients.
 */
void bunga_server_broadcast(struct bunga_server_t *self_p);

/**
 * Disconnect given client. If given client is NULL, the currect
 * client is disconnected.
 */
void bunga_server_disconnect(
    struct bunga_server_t *self_p,
    struct bunga_server_client_t *client_p);

/**
 * Prepare a execute_command_rsp message. Call `send()`, `reply()` or `broadcast()`
 * to send it.
 */
struct bunga_execute_command_rsp_t *bunga_server_init_execute_command_rsp(
    struct bunga_server_t *self_p);

#endif
