dist: xenial

language: c

before_install:
  - source setup.sh
  - python3 --version
  - pip3 install nala

script:
  - make -j $(cat /proc/cpuinfo | grep processor | wc -l) run

after_success:
  - bash <(curl -s https://codecov.io/bash)
