dist: bionic

language: python

python:
  - "3.7"

install:
  - source setup.sh
  - pip install nala

script:
  - make -s -j $(nproc) run SANITIZE=yes
  - make -s -j $(nproc) library
  - make install PREFIX=root

after_success:
  - bash <(curl -s https://codecov.io/bash)
