language: python

python:
  - "3.7"

install:
  - source setup.sh
  - pip install nala

script:
  - make -j $(cat /proc/cpuinfo | grep processor | wc -l) run

after_success:
  - bash <(curl -s https://codecov.io/bash)
