language: python

python:
  - "3.7"

install:
  - source setup.sh
  - pip install nala

script:
  - make -s -j $(cat /proc/cpuinfo | grep processor | wc -l) run
  - make -s -j $(cat /proc/cpuinfo | grep processor | wc -l) library
  - make install PREFIX=root

after_success:
  - bash <(curl -s https://codecov.io/bash)
