TESTS += test_bus.c
TESTS += test_device_mapper.c
TESTS += test_dhcp_client.c
TESTS += test_log_object.c
TESTS += test_message.c
TESTS += test_ml.c
TESTS += test_network.c
TESTS += test_ntp_client.c
TESTS += test_queue.c
TESTS += test_rtc.c
TESTS += test_shell.c
TESTS += test_timer.c
TESTS += test_worker_pool.c

include $(ML_ROOT)/make/suite.mk
